sudo: false
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install tox-travis
- pip install -r requirements.txt
- pip install codecov
after_success:
- codecov
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  on:
    tags: true
    repo: scrapinghub/js2xml
    condition: "$TRAVIS_PYTHON_VERSION = '3.6'"
